//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnvironmentCanadaScrap.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        static global::System.Resources.ResourceManager resourceMan;
        
        static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EnvironmentCanadaScrap.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;!--APNote: class had to be renamed to ecClass (as collides with the reserved word). --&gt;
        ///&lt;climatedata xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; &gt;
        ///	&lt;lang&gt;ENG&lt;/lang&gt;
        ///	&lt;stationinformation climateid=&quot;6158733&quot; wmoid=&quot;71624&quot;&gt;YYZ&lt;/stationinformation&gt;
        ///	&lt;month index=&quot;1&quot;&gt;
        ///		&lt;day index=&quot;1&quot;&gt;
        ///			&lt;temperature ecClass=&quot;extremeMax&quot; units=&quot;°C&quot; unitType=&quot;metric&quot; year=&quot;2007&quot; period=&quot;1939-2009&quot;&gt;9.20&lt;/temperature&gt;
        ///			&lt;temperature ecClass=&quot;extremeMin&quot; units=&quot;°C&quot; unitTyp [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WholeYear {
            get {
                return ResourceManager.GetString("WholeYear", resourceCulture);
            }
        }
    }
}
