//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnvironmentCanadaScrap.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int LightWindMaximum {
            get {
                return ((int)(this["LightWindMaximum"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"45151,smc,Lake Simcoe,1|45137,ngb,North Georgian Bay,0|45143,sgb,South Georgian Bay,1|45139,wlo,West Lake Ontario,1|45135,elo,East Lake Ontario,0|45149,slh,South Lake Huron,0|45008,msh,Mid South Huron,1|45003,nlh,North Lake Huron,1|45132,wle,West Lake Erie,0|45142,ele,East Lake Erie,0")]
        public string SiteList {
            get {
                return ((string)(this["SiteList"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://text.www.weatheroffice.gc.ca/marine/weatherConditions-24hrObsHistory_e.htm" +
            "l?mapID=10&siteID=08300&stationID={0}")]
        public string ECUrl24hourTemplate {
            get {
                return ((string)(this["ECUrl24hourTemplate"]));
            }
        }
    }
}
