global using System;
global using System.Collections.Generic;
global using System.Data.Entity;
global using System.Diagnostics;
global using System.IO;
global using System.Linq;
global using System.Threading.Tasks;
global using Db.EventLog.DbModel;
global using Db.EventLog.Ext;
//obal using System.Text.Json; //tu: new and very performant Json lib (Dec 2021)
global using Db.EventLog.Main;
global using StandardLib.Extensions;
global using StandardLib.Extensions;
global using Db.EventLog.Ext;
global using System;
global using System.Data.Entity;
global using System.Diagnostics;
global using System.IO;
global using StandardLib.Helpers;
