global using System;
global using System.Collections.Generic;
global using System.ComponentModel;
global using System.Diagnostics;
global using System.Diagnostics.Eventing.Reader;
global using System.Linq;
global using System.Reflection;
global using System.Threading.Tasks;
global using System.Windows;
global using System.Windows.Controls;
global using System.Windows.Media;
global using System.Windows.Shapes;
global using AAV.Sys.Ext;
global using AAV.Sys.Helpers;
global using AAV.WPF.Ext;
global using AsLink;
global using Db.EventLog.DbModel;
//obal using System.Text.Json; //tu: new and very performant Json lib (Dec 2021)
global using Db.EventLog.Main;
global using Microsoft.Expression.Shapes;
global using Microsoft.Win32;
global using StandardLib.Services;
global using UpTimeChart;
global using static System.Diagnostics.Trace;
