global using System;
global using System.ComponentModel;
global using System.Diagnostics;
global using System.IO;
global using System.Linq;
global using System.Net.Http.Headers;
//obal using static System.Diagnostics.Trace;
global using System.Threading;
global using System.Threading.Tasks;
global using System.Windows;
global using System.Windows.Controls;
global using System.Windows.Media.Animation;
global using System.Windows.Media.Imaging;
global using System.Windows.Threading;
global using AmbienceLib;
global using DemoLibrary;
global using LibVLCSharp.Shared;
global using Microsoft.Extensions.Logging;
global using Microsoft.Graph;
global using StandardContractsLib;
global using StandardLib.Helpers;
global using WpfUserControlLib.Extensions;
global using WpfUserControlLib.Services;
global using LogLevel = Microsoft.Extensions.Logging.LogLevel;
