global using System;
global using System.Data;
global using System.Diagnostics;
global using System.IO;
global using System.Linq;
global using System.Threading;
global using System.Threading.Tasks;
global using System.Windows;
global using System.Windows.Controls;
global using System.Windows.Documents;
global using System.Windows.Input;
//obal using DB.Inventory.Models;
global using System.Windows.Media;
global using OleksaScrSvr.VM.VMs;
global using StandardLib.Helpers;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.Logging;
global using static System.Diagnostics.Trace;
global using static System.Media.SystemSounds;
global using WpfUserControlLib.Base;
global using WpfUserControlLib.Extensions;
global using OleksaScrSvr.Contract;
global using System.Collections.ObjectModel;
