global using System;
global using System.Diagnostics;
global using System.Reflection;
global using System.Threading.Tasks;
global using System.Windows;
global using System.Windows.Controls;
global using System.Windows.Markup;
global using AmbienceLib;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Logging;
global using OleksaScrSvr.VM;
global using StandardContractsLib;
global using StandardLib.Helpers;
global using WpfUserControlLib.Helpers;
global using static System.Diagnostics.Trace;
global using System.IO;
